openapi: 3.0.3
info:
  title: REal Estate API
  description: API for the real estate Service
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
paths:
  /login:
    $ref: ./paths/user/v1/login.yaml
  /register:
    $ref: ./paths/user/v1/register.yaml
  /user/{username}:
    $ref: ./paths/user/v1/userByUsername.yaml
  /users:
    $ref: ./paths/user/v1/users.yaml
  /objects:
    $ref: ./paths/property/v1/properties.yaml
  /object:
    $ref: ./paths/property/v1/property.yaml
  /object/{id}:
    $ref: ./paths/property/v1/propertyById.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT